USE sakila;

-- 1. List the number of films per category.
SELECT
    c.name AS category,
    COUNT(fc.film_id) AS number_of_films
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY number_of_films DESC;


-- 2. Retrieve the store ID, city and country for each store.
SELECT
    s.store_id,
    ci.city,
    co.country
FROM store AS s
JOIN address AS a
    ON s.address_id = a.address_id
JOIN city AS ci
    ON a.city_id = ci.city_id
JOIN country AS co
    ON ci.country_id = co.country_id
ORDER BY s.store_id;


-- 3. Calculate the total revenue generated by each store in dollars.
SELECT
    s.store_id,
    ROUND(SUM(p.amount), 2) AS total_revenue
FROM store AS s
JOIN staff AS st
    ON s.store_id = st.store_id
JOIN payment AS p
    ON st.staff_id = p.staff_id
GROUP BY s.store_id
ORDER BY s.store_id;


-- 4. Determine the average running time of films for each category.
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY average_running_time DESC;


-- 5. Identify the film category with the longest average running time.
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY average_running_time DESC
LIMIT 1;


-- 6. Display the top 10 most frequently rented movies.
SELECT
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM film AS f
JOIN inventory AS i
    ON f.film_id = i.film_id
JOIN rental AS r
    ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC, f.title
LIMIT 10;


-- 7. Determine if Academy Dinosaur can currently be rented from Store 1.
SELECT
    f.title,
    CASE
        WHEN COUNT(i.inventory_id) > 0 THEN 'Available'
        ELSE 'Not available'
    END AS availability
FROM film AS f
LEFT JOIN inventory AS i
    ON f.film_id = i.film_id
    AND i.store_id = 1
    AND NOT EXISTS (
        SELECT 1
        FROM rental AS r
        WHERE r.inventory_id = i.inventory_id
          AND r.return_date IS NULL
    )
WHERE f.title = 'Academy Dinosaur'
GROUP BY f.film_id, f.title;


-- 8. List all film titles with their current inventory availability.
SELECT
    f.title,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM inventory AS i
            WHERE i.film_id = f.film_id
              AND NOT EXISTS (
                  SELECT 1
                  FROM rental AS r
                  WHERE r.inventory_id = i.inventory_id
                    AND r.return_date IS NULL
              )
        ) THEN 'Available'
        ELSE 'Not available'
    END AS availability
FROM film AS f
ORDER BY f.title;
