-- Q1 List the number of films per category
SELECT *
FROM category;

SELECT *
FROM film_category;

SELECT *
FROM category AS c
JOIN film_category AS fc
ON c.category_id = fc.category_id;

SELECT c.name, COUNT(fc.film_id) AS number_of_films
FROM category AS c
JOIN film_category AS fc
ON c.category_id = fc.category_id
GROUP BY c.name;

-- Q2 Retrieve the store ID, city and country for each store
SELECT 
s.store_id,
ci.city,
co.country
FROM store AS s
JOIN address AS a
ON s.address_id = a.address_id
JOIN city AS ci
ON a.city_id = ci.city_id
JOIN country AS co
ON ci.country_id = co.country_id;
    
-- Q3 Calculate the total revenue generated by each store in dollars
SELECT 
s.store_id,
SUM(p.amount) AS total_revenue
FROM store AS s
JOIN staff AS st
ON s.store_id = st.store_id
JOIN payment AS p
ON st.staff_id = p.staff_id
GROUP BY s.store_id;

SELECT 
s.store_id,
CONCAT('$', ROUND(SUM(p.amount), 2)) AS total_revenue
FROM store AS s
JOIN staff AS st
ON s.store_id = st.store_id
JOIN payment AS p
ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- Q4: Determine the average running time of films for each category
SELECT
    c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
JOIN film_category AS fc
    ON c.category_id = fc.category_id
JOIN film AS f
    ON fc.film_id = f.film_id
GROUP BY c.name;
    